<?
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["market"]["7"]="W";
$PERM["vendors"]["7"]="W";
$PERM["reviews"]["7"]="W";
$PERM["promotions"]["7"]="W";
$PERM["personal"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>