<?
$aMenuLinks = Array(
	Array(
		"Каталог", 
		"/market/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Видеоглазки", 
		"/market/videoglazki/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"GSM Розетки", 
		"/market/umnyj-dom/kontrollery-upravleniya-pitaniem/rozetki/gsm-rozetki/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"GSM Сигнализации", 
		"/market/signalizatsii/okhrannye-signalizatsii/gsm_signalizacii1/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Видеонаблюдение", 
		"/market/videonablyudenie/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"GPS Трекеры Маяки", 
		"/market/gps-trekery/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Видеодомофоны", 
		"/market/videodomofony/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Источники питания", 
		"/market/istochniki-pitaniya/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>