<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?
$SNIPPETS = Array();
$SNIPPETS['snippet0011.snp'] = Array('title' => 'Почему Русмарта?');
$SNIPPETS['Отзывы/snippet0001.snp'] = Array('title' => 'Отзывы Розетки');
$SNIPPETS['Отзывы/snippet0002.snp'] = Array('title' => 'Отзывы видеонаблюдение');
$SNIPPETS['Отзывы/snippet0003.snp'] = Array('title' => 'Плеер');
$SNIPPETS['Отзывы/snippet0004.snp'] = Array('title' => 'Отзывы фотоловушки');
$SNIPPETS['Отзывы/snippet0005.snp'] = Array('title' => 'Отзывы Видеоглазки');
$SNIPPETS['Отзывы/snippet0006.snp'] = Array('title' => 'Отзывы Сигнализации');
$SNIPPETS['Сертификаты/snippet0001.snp'] = Array('title' => 'Сертификаты Видеоглазки');
$SNIPPETS['Сертификаты/snippet0002.snp'] = Array('title' => 'Сертификаты Видеонаблюдение');
$SNIPPETS['Сертификаты/snippet0003.snp'] = Array('title' => 'Сертификаты Сигнализации');
$SNIPPETS['Видеоролики/snippet0001.snp'] = Array('title' => 'Видео IP 1Mp');
$SNIPPETS['Видеоролики/snippet0002.snp'] = Array('title' => 'Видео AHD 1MP');
$SNIPPETS['Видеоролики/snippet0003.snp'] = Array('title' => 'Видео AHD 2MP');
$SNIPPETS['Видеоролики/snippet0004.snp'] = Array('title' => 'Видео IP 2Mp');
$SNIPPETS['Сертификаты/snippet0004.snp'] = Array('title' => 'Дипломы');
$SNIPPETS['snippet0002.snp'] = Array('title' => 'Комплектация фотоловушек');
$SNIPPETS['snippet0003.snp'] = Array('title' => 'Примеры снимков и видео');
$SNIPPETS['snippet0005.snp'] = Array('title' => 'Текст описания фотоловушки');
$SNIPPETS['snippet0006.snp'] = Array('title' => 'Варианты конфигурации видеорегистратора');
$SNIPPETS['Программное обеспечение/snippet0001.snp'] = Array('title' => 'Приложение Xmeye + Диск с ПО +IE8');
$SNIPPETS['Программное обеспечение/snippet0002.snp'] = Array('title' => 'Приложение N_EYE');
$SNIPPETS['Программное обеспечение/snippet0003.snp'] = Array('title' => 'Приложение IP PRO для WIFI комплектов');
$SNIPPETS['Программное обеспечение/snippet0004.snp'] = Array('title' => 'Приложение SEETONG');
$SNIPPETS['Программное обеспечение/snippet0005.snp'] = Array('title' => 'Приложение YOOSEE');
$SNIPPETS['Программное обеспечение/snippet0006.snp'] = Array('title' => 'Приложение NVSIP');
$SNIPPETS['Программное обеспечение/snippet0007.snp'] = Array('title' => 'Приложение VR CAM');
$SNIPPETS['Программное обеспечение/snippet0008.snp'] = Array('title' => 'Приложение COT PRO');
$SNIPPETS['snippet0008.snp'] = Array('title' => 'Схема подключения AHD комплектов');
$SNIPPETS['Программное обеспечение/snippet0009.snp'] = Array('title' => 'Приложение CMS для Windows для HC102E');
$SNIPPETS['snippet0009.snp'] = Array('title' => 'Схема подключения IP комплектов видеонаблюдения');
$SNIPPETS['Видеоролики/snippet0005.snp'] = Array('title' => 'Live 1МП Гематология');
$SNIPPETS['Видеоролики/snippet0006.snp'] = Array('title' => 'Live 2МП Москва');
$SNIPPETS['Программное обеспечение/snippet0010.snp'] = Array('title' => 'Приложение CMS для Windows G90B, H510');
$SNIPPETS['Программное обеспечение/snippet0011.snp'] = Array('title' => 'Приложение для Jimi JH08');
$SNIPPETS['Таблицы особенностей/snippet0001.snp'] = Array('title' => 'Таблица Особенности для фотоловушек');
$SNIPPETS['Программное обеспечение/snippet0012.snp'] = Array('title' => 'Настройки для фотоловушек');
$SNIPPETS['Программное обеспечение/snippet0013.snp'] = Array('title' => 'Программа MMSConfig ');
$SNIPPETS['Таблицы особенностей/snippet0002.snp'] = Array('title' => 'Таблица Особенности для видеонаблюдения');
$SNIPPETS['Таблицы особенностей/snippet0003.snp'] = Array('title' => 'Таблица особенностей для экшн камер');
$SNIPPETS['Таблицы особенностей/snippet0004.snp'] = Array('title' => 'Таблица особенностей для домофонов');
$SNIPPETS['snippet0001.snp'] = Array('title' => 'Отзывы от администрации');
$SNIPPETS['Видеоролики/snippet0007.snp'] = Array('title' => 'Настройка фотоловушки HC550G');
$SNIPPETS['Сертификаты/snippet0005.snp'] = Array('title' => 'GSM управление, GSM розетки');
$SNIPPETS['Сертификаты/snippet0006.snp'] = Array('title' => 'Сигнализации');
$SNIPPETS['Сертификаты/snippet0007.snp'] = Array('title' => 'AHD_Видеонаблюдение');
$SNIPPETS['Программное обеспечение/snippet0014.snp'] = Array('title' => 'Приложения для Premium 2');
$SNIPPETS['snippet0004.snp'] = Array('title' => 'Приложение CamHi');
$SNIPPETS['Программное обеспечение/snippet0015.snp'] = Array('title' => 'Приложение CamHi');
$SNIPPETS['snippet0007.snp'] = Array('title' => 'Знаки доверия по центру');
$SNIPPETS['snippet0010.snp'] = Array('title' => 'XMeye и CMS');
$SNIPPETS['Программное обеспечение/snippet0016.snp'] = Array('title' => 'Для 5 Mp');
$SNIPPETS['Анонс/snippet0001.snp'] = Array('title' => 'Баннер в анонсе');
$SNIPPETS['snippet0012.snp'] = Array('title' => 'Start_CMS');
$SNIPPETS['Анонс/snippet0002.snp'] = Array('title' => 'Гарантия 3г');
$SNIPPETS['snippet0013.snp'] = Array('title' => 'Калькулятор HDD');
$SNIPPETS['Анонс/snippet0003.snp'] = Array('title' => '3 года и спасибо');
?>